force-app/main/default/objects/psa_Filament__c/psa_Filament__c.object-meta.xml
<CustomObject>
    <description>Printer filaments</description>
    <label>Filament</label>
    <nameField>
        <label>Filament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/psa_Filament__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Filament Color</description>
    <label>Color</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/psa_Filament__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manufacturer of the filament</description>
    <label>Manufacturer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Filaments</relationshipLabel>
    <relationshipName>Filaments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/psa_Filament__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <description>Material of the filament</description>
    <label>Material</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>psa_Material</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/psa_Filament__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>Spool Size</description>
    <label>Size (g)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/psa_Print__c/psa_Print__c.object-meta.xml
<CustomObject>
    <description>Prints for a project</description>
    <label>Print</label>
    <nameField>
        <label>Print Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/psa_Print__c/fields/Filament__c.field-meta.xml
<CustomField>
    <fullName>Filament__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Filament</description>
    <label>Filament</label>
    <referenceTo>psa_Filament__c</referenceTo>
    <relationshipLabel>Prints</relationshipLabel>
    <relationshipName>Prints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/psa_Print__c/fields/Printer__c.field-meta.xml
<CustomField>
    <fullName>Printer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Printer</description>
    <label>Printer</label>
    <referenceTo>psa_Printer__c</referenceTo>
    <relationshipLabel>Prints</relationshipLabel>
    <relationshipName>Prints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/psa_Print__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master lookup to Project</description>
    <label>Project</label>
    <referenceTo>psa_Project__c</referenceTo>
    <relationshipLabel>Prints</relationshipLabel>
    <relationshipName>Prints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/psa_Print__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the print.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/psa_Printer__c/psa_Printer__c.object-meta.xml
<CustomObject>
    <label>Printer</label>
    <nameField>
        <label>Printer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Printers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/psa_Printer__c/fields/Additional_Features__c.field-meta.xml
<CustomField>
    <fullName>Additional_Features__c</fullName>
    <description>Additional features of the printer</description>
    <label>Additional Features</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/psa_Printer__c/fields/Connectivity__c.field-meta.xml
<CustomField>
    <fullName>Connectivity__c</fullName>
    <description>Connectivity of the printer</description>
    <inlineHelpText>How are prints initiated.</inlineHelpText>
    <label>Connectivity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Octoprint</fullName>
            </value>
            <value>
                <fullName>Klipper</fullName>
            </value>
            <value>
                <fullName>SD-Card</fullName>
            </value>
            <value>
                <fullName>USB</fullName>
            </value>
            <value>
                <fullName>Proprietary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/psa_Printer__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Lookup for Manufacturer</description>
    <label>Manufacturer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Printers</relationshipLabel>
    <relationshipName>Printers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/psa_Printer__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Model of the printer</description>
    <label>Model</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/psa_Printer__c/fields/Network_Name__c.field-meta.xml
<CustomField>
    <fullName>Network_Name__c</fullName>
    <description>FQN or IP of the Printer</description>
    <inlineHelpText>Enter in the FQN or IP of the Printer</inlineHelpText>
    <label>Network Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/psa_Printer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Availability of the Printer</description>
    <inlineHelpText>Select whether the Printer is usable or down.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
                <default>true</default>
                <label>Online</label>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/psa_Printer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Printer Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FDM - Cartesian</fullName>
                <default>true</default>
                <label>FDM - Cartesian</label>
            </value>
            <value>
                <fullName>FDM - Delta</fullName>
            </value>
            <value>
                <fullName>SLA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/psa_Project__c/psa_Project__c.object-meta.xml
<CustomObject>
    <description>Print Project management</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/psa_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the project</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>Designing</fullName>
            </value>
            <value>
                <fullName>Building</fullName>
            </value>
            <value>
                <fullName>Assembling</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/psa_Material.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PLA</fullName>
    </customValue>
    <customValue>
        <fullName>PETG</fullName>
    </customValue>
    <customValue>
        <fullName>FLEX</fullName>
    </customValue>
    <customValue>
        <fullName>PC-CF</fullName>
    </customValue>
    <customValue>
        <fullName>PC Blend</fullName>
    </customValue>
    <customValue>
        <fullName>ABS</fullName>
    </customValue>
    <description>Material Type</description>
    <masterLabel>Material</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/psa_BasicTest.cls
/* Basic Test Class to test the functionality of the Print Shop App
* Test creation of Printer, Jobs, Projects, and Upgrades.
*/
@isTest
public class psa_BasicTest {
    // Test Setup
    @TestSetup
    static void testPrintShopData(){
        // Create a test Manufacturer
        Account testManufacturer = new Account(Name='Prusa Research',Industry='Manufacturing');
        insert testManufacturer;
        
        // Create Printer
        psa_Printer__c testPrinter = new psa_Printer__c(Name='MK3S',Manufacturer__c=testManufacturer.Id,Model__c='i3 MK3S+',Network_Name__c='OctoMK3S',Connectivity__c='OctoPrint',Status__c='Online',Type__c='FDM - Cartesian',Additional_Features__c='Direct-Drive;Enclosed;Air Filtration');
        insert testPrinter;
        
        // Create Filament
        psa_Filament__c testFDM = new psa_Filament__c(Name='Prusa Orange PETG',Manufacturer__c=testManufacturer.Id,Color__c='Orange',Size__c=1000,Material__c='PETG');
        insert testFDM;
        
        // Create Project
        psa_Project__c testProject = new psa_Project__c(Name='Pi4 Case');
        insert testProject;
    }
    @isTest
    static void printJobTest(){
        //Query test setup records
		psa_Project__c proj = [SELECT Id FROM psa_Project__c LIMIT 1];
        psa_Printer__c printer = [SELECT Id FROM psa_Printer__c LIMIT 1];
        psa_Filament__c filament = [SELECT Id FROM psa_Filament__c LIMIT 1];
        
        // Create Print Job
        test.startTest();
            psa_Print__c testPrint = new psa_Print__c(Name='Case',Project__c=proj.Id,Printer__c=printer.Id,Filament__c=filament.Id);
            insert testPrint;
        test.stopTest();
        
        psa_Print__c validPrint = [SELECT Id, Name FROM psa_Print__c LIMIT 1];
        System.assertEquals('Case',validPrint.Name,'Print was not created');
        
        // Update Printer to offline w/o Reason (negative test)
    }
}